extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - standard
  - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - prettier
root: true
rules:
  no-useless-constructor: off
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/no-non-null-assertion': off
  'prettier/prettier': "error"
env:
  browser: true
  jest: true
globals:
  test: writable
  expect: readonly
