version: 2.1

orbs:
  node: circleci/node@5.1.0
  codecov: codecov/codecov@3.2.4

jobs:
  tests:
    docker:
      - image: cimg/node:16.17.1-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            sudo corepack enable
            sudo corepack prepare pnpm --activate
      - run:
          name: Show node version
          command: node --version
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run:
          name: Run lint check
          command: npm run lint
      - run:
          name: Run unit tests with coverage
          command: npm run test
      - codecov/upload:
          file: coverage/*.json
  versioning:
    docker:
      - image: cimg/node:16.17.1
    steps:
      - checkout
      - run:
          name: Check package version
          command: node tools/check-version be-community watermarkjs main

workflows:
  ci:
    jobs:
      - tests
      - versioning:
          filters:
            branches:
              ignore: 
                - main
                - dev
            tags:
              ignore: /.*/